export DESIGN_NICKNAME ?= snitch_cluster
export DESIGN_NAME = snitch_cluster_wrapper
export PLATFORM    = asap7

-include $(BENCH_DESIGN_HOME)/src/$(DESIGN_NICKNAME)/verilog.mk

export SDC_FILE      = $(BENCH_DESIGN_HOME)/$(PLATFORM)/snitch_cluster/constraint.sdc

# Skip SVA assertions
export VERILOG_DEFINES = -D VERILATOR

# SRAM macros generated by bsg_fakeram (auto-generated by setup.sh)
-include $(BENCH_DESIGN_HOME)/src/$(DESIGN_NICKNAME)/dev/generated/sram_macros.mk
export ADDITIONAL_LEFS = $(SRAM_LEFS)
export ADDITIONAL_LIBS = $(SRAM_LIBS)

# Allow remaining small memories to be synthesized as FFs
# Large SRAMs (512x64 TCDM, 128x512 ICache, 64x512 DMA) are mapped to fakerams in tc_sram.sv
export SYNTH_MEMORY_MAX_BITS = 8193

# Hierarchical synthesis: keeps module boundaries, reduces placement complexity
export SYNTH_HIERARCHICAL = 1
export SYNTH_ARGS = -noshare

export DIE_AREA  = 0 0 1500 1500
export CORE_AREA = 5 5 1495 1495
export PLACE_DENSITY = 0.35
export MACRO_PLACE_HALO = 2 2

# Skip CTS repair_timing: hold violations from async reset fanout cause infinite loop;
# hold fixing is deferred to the route stage
export SKIP_CTS_REPAIR_TIMING = 1
