#!/usr/bin/env python3
"""Generate designs/<platform>/bp_processor/macros.v.

The Black-Parrot BSG library uses ``bsg_mem_1rw_sync_synth`` and
``bsg_mem_1rw_sync_mask_write_bit_synth`` for its parameterised memory
arrays. This script emits a macros.v that:

  - for each (depth, width) in ``LARGE_CONFIGS``: instantiates the
    matching ``fakeram_DxW_1rw`` macro (bsg_fakeram-generated LEF/LIB
    + behavioural .v), wiring the new ``rw0_*`` pin names.
  - for any other (depth, width): falls back to a register-array
    implementation, which yosys synthesises to flip-flops.

The implicit-mask flavour (``bsg_mem_1rw_sync_synth``) broadcasts
``w_i`` across all wmask bits; the per-bit-mask flavour passes
``w_mask_i`` straight through. Both use the same ``rw0_wmask_in[W-1:0]``
fakeram pin (per-bit granularity is enabled in the cfg via
``write_granularity: 1``).

Sizes intentionally excluded from ``LARGE_CONFIGS``:

  - 32x66 (2112 bits) and 8x174 (1392 bits): CACTI cannot size these
    on nangate45 (D=32 or D=8 too shallow for a 66- or 174-wide row);
    for consistency they are flip-flops on asap7 too. Both are above
    the historical 1024-bit threshold but fall through the FF branch.

Run::

    python3 designs/src/bp_processor/dev/gen_macros_v.py

The output is written to designs/asap7/bp_processor/macros.v and
designs/nangate45/bp_processor/macros.v (same content — bp_processor
uses the same RTL on both platforms).
"""
import os

# (depth, width) pairs that bsg_fakeram emits as hard macros.
# Keep names in sync with the cfgs at designs/src/bp_processor/dev/generated/.
LARGE_CONFIGS = [
    (512,  64),
    ( 64, 184),
    (512,   8),
    ( 64,  50),
    ( 32,  48),
    (128,   8),
]

# Where the generated macros.v lands. Same content per platform.
OUTPUT_DIRS = [
    "designs/asap7/bp_processor",
    "designs/nangate45/bp_processor",
    "designs/sky130hd/bp_processor",
]


HEADER = """\
// Auto-generated by designs/src/bp_processor/dev/gen_macros_v.py — do not edit.
//
// Large memories (listed below) bind to bsg_fakeram-generated
// fakeram_DxW_1rw macros via the rw0_* pin convention. Everything else
// falls through to a behavioural register array (synthesises to FFs).
"""

# A single fakeram_DxW_1rw instantiation with bsg_fakeram's port-index pin
# names. ``wmask_expr`` is the expression bound to rw0_wmask_in.
INSTANCE_TMPL = """\
\t\telse if ((els_p == {depth}) && (width_p == {width})) begin : fakeram_{depth}x{width}
\t\t\tfakeram_{depth}x{width}_1rw mem (
\t\t\t\t.rw0_clk(clk_i),
\t\t\t\t.rw0_ce_in(v_i),
\t\t\t\t.rw0_we_in(w_i),
\t\t\t\t.rw0_wmask_in({wmask_expr}),
\t\t\t\t.rw0_addr_in(addr_i),
\t\t\t\t.rw0_wd_in(data_i),
\t\t\t\t.rw0_rd_out(data_o)
\t\t\t);
\t\tend
"""


# Implicit-mask flavour ({W{w_i}} broadcast). Body is wrapped by a module
# template below.
def make_module(name, mask_signal):
    """Build one bsg_mem_*_synth module. ``mask_signal`` is the expression
    bound to ``rw0_wmask_in`` — either ``{W{w_i}}`` (implicit mask, write
    enables every bit) or ``w_mask_i`` (per-bit mask flavour)."""
    fakeram_blocks = []
    for depth, width in LARGE_CONFIGS:
        if mask_signal == "broadcast":
            wmask_expr = f"{{{width}{{w_i}}}}"
        else:
            wmask_expr = mask_signal
        fakeram_blocks.append(INSTANCE_TMPL.format(
            depth=depth, width=width, wmask_expr=wmask_expr))

    # Header / ports / parameter declarations differ slightly between
    # the two wrapper modules — keep them inline for readability.
    if name == "bsg_mem_1rw_sync_synth":
        ports = "clk_i,\n\tv_i,\n\treset_i,\n\tdata_i,\n\taddr_i,\n\tw_i,\n\tdata_o"
        port_decls = (
            "\tinput clk_i;\n"
            "\tinput v_i;\n"
            "\tinput reset_i;\n"
            "\tinput [(width_p < 1 ? 0 : width_p - 1):0] data_i;\n"
            "\tinput [addr_width_lp - 1:0] addr_i;\n"
            "\tinput w_i;\n"
            "\toutput wire [(width_p < 1 ? 0 : width_p - 1):0] data_o;"
        )
        zero_used = "&{clk_i, v_i, data_i, addr_i, w_i}"
    else:  # bsg_mem_1rw_sync_mask_write_bit_synth
        ports = "clk_i,\n\treset_i,\n\tdata_i,\n\taddr_i,\n\tv_i,\n\tw_mask_i,\n\tw_i,\n\tdata_o"
        port_decls = (
            "\tinput clk_i;\n"
            "\tinput reset_i;\n"
            "\tinput [(width_p < 1 ? 0 : width_p - 1):0] data_i;\n"
            "\tinput [addr_width_lp - 1:0] addr_i;\n"
            "\tinput v_i;\n"
            "\tinput [(width_p < 1 ? 0 : width_p - 1):0] w_mask_i;\n"
            "\tinput w_i;\n"
            "\toutput wire [(width_p < 1 ? 0 : width_p - 1):0] data_o;"
        )
        zero_used = "&{clk_i, data_i, addr_i, v_i, w_mask_i, w_i}"

    blocks = "".join(fakeram_blocks)
    return f"""\
module {name} (
\t{ports}
);
\tparameter width_p = 0;
\tparameter els_p = 0;
\tparameter latch_last_read_p = 0;
\tparameter addr_width_lp = ((els_p == 1) || (els_p == 0) ? 1 : $clog2(els_p));
\tparameter verbose_p = 1;
{port_decls}
\twire unused = reset_i;
\tgenerate
\t\tif ((width_p == 0) || (els_p == 0)) begin : z
\t\t\twire unused0 = {zero_used};
\t\t\tassign data_o = 1'sb0;
\t\tend
{blocks}\t\telse begin : nz
\t\t\treg [addr_width_lp - 1:0] addr_r;
\t\t\treg [width_p - 1:0] mem [els_p - 1:0];
\t\t\twire read_en;
\t\t\twire [width_p - 1:0] data_out;
\t\t\twire [addr_width_lp - 1:0] addr_li = (els_p > 0 ? addr_i : {{addr_width_lp {{1'sb0}}}});
\t\t\tassign read_en = v_i & ~w_i;
\t\t\tassign data_out = mem[addr_r];
\t\t\talways @(posedge clk_i)
\t\t\t\tif (read_en)
\t\t\t\t\taddr_r <= addr_li;
\t\t\t\telse
\t\t\t\t\taddr_r <= 1'sbx;
\t\t\tassign data_o = data_out;
\t\t\talways @(posedge clk_i)
\t\t\t\tif (v_i & w_i)
\t\t\t\t\tmem[addr_li] <= data_i;
\t\tend
\tendgenerate
endmodule
"""


def main():
    body = HEADER + "\n"
    body += make_module("bsg_mem_1rw_sync_synth", "broadcast")
    body += "\n"
    body += make_module("bsg_mem_1rw_sync_mask_write_bit_synth", "w_mask_i")

    # Locate the repo root: this script lives at designs/src/bp_processor/dev/
    here = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.normpath(os.path.join(here, "..", "..", "..", ".."))

    for rel in OUTPUT_DIRS:
        path = os.path.join(repo_root, rel, "macros.v")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as fid:
            fid.write(body)
        print(f"wrote {os.path.relpath(path, repo_root)}")


if __name__ == "__main__":
    main()
