#!/usr/bin/env bash
# Build script for Black-Parrot RISC-V processor.
# Generates file lists and include paths from bp_top/flist.vcs for
# direct SystemVerilog synthesis via yosys-slang.
#
# yosys-slang handles parameter elaboration natively, so bp_params_p
# can be set via VERILOG_TOP_PARAMS at synthesis time to select
# different core configurations (unicore, quad-core, etc.).

set -eu

DIR="$(dirname "$(readlink -f "$0")")"
cd "$DIR"

# ── Check that BP repo is initialized ───────────────────────────────────
BP_REPO="$(pwd)/repo"
if [ ! -d "$BP_REPO/bp_top" ]; then
    echo "Error: Black-Parrot repo not found at $BP_REPO."
    echo "Run: git submodule update --init designs/src/bp_processor/dev/repo"
    exit 1
fi

# ── Fetch BP dependencies (external submodules) ────────────────────────
if [ ! -d "$BP_REPO/external/basejump_stl/bsg_misc" ]; then
    echo "Fetching Black-Parrot dependencies..."
    cd "$BP_REPO"
    git submodule update --init --recursive
    cd "$DIR"
else
    echo "Black-Parrot dependencies already present"
fi

# ── Parse flist.vcs to extract file lists and include dirs ────────────
echo "Parsing bp_top/flist.vcs..."

FLIST="$BP_REPO/bp_top/flist.vcs"
if [ ! -f "$FLIST" ]; then
    echo "Error: $FLIST not found" >&2
    exit 1
fi

mkdir -p generated

FILES=()
INCLUDES=()

while IFS= read -r line; do
    line="${line%%//*}"
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [ -z "$line" ] && continue
    [[ "$line" == \#* ]] && continue
    line="${line//\$BP_DIR/$BP_REPO}"

    if [[ "$line" == +incdir+* ]]; then
        inc_path="${line#+incdir+}"
        if [ -d "$inc_path" ]; then
            INCLUDES+=("$(realpath --relative-to="$DIR" "$inc_path")")
        else
            echo "Warning: include dir not found: $inc_path"
        fi
    elif [[ "$line" == +* ]] || [[ "$line" == -* ]]; then
        continue
    elif [ -f "$line" ]; then
        FILES+=("$(realpath --relative-to="$DIR" "$line")")
    else
        echo "Warning: source file not found: $line"
    fi
done < "$FLIST"

echo "Found ${#FILES[@]} source files and ${#INCLUDES[@]} include dirs"

# ── Write file lists ──────────────────────────────────────────────────
printf '%s\n' "${FILES[@]}" > generated/files.txt
printf '%s\n' "${INCLUDES[@]}" > generated/includes.txt

# ── (FakeRAM LEF/LIB are now generated by tools/regenerate_sram.sh
#     from designs/src/bp_processor/dev/generated/fakeram_<platform>.cfg;
#     macros.v is regenerated by dev/gen_macros_v.py.  Both are committed,
#     so a plain submodule bump that doesn't change the memory config does
#     not need to re-run either step.)

# ── Generate Bazel-compatible source list ──────────────────────────────
# Write a .bzl file that BUILD.bazel can load() to get the file list.
{
    echo 'BP_SRCS = ['
    for f in "${FILES[@]}"; do
        echo "    \"dev/$f\","
    done
    echo ']'
    echo ''
    echo 'BP_INCLUDES = ['
    for d in "${INCLUDES[@]}"; do
        echo "    \"dev/$d\","
    done
    echo ']'
    echo ''
    # Space-separated include dirs for VERILOG_INCLUDE_DIRS argument
    echo -n 'BP_INCLUDE_DIRS_STR = "'
    first=true
    for d in "${INCLUDES[@]}"; do
        if [ "$first" = true ]; then
            echo -n "designs/src/bp_processor/dev/$d"
            first=false
        else
            echo -n " designs/src/bp_processor/dev/$d"
        fi
    done
    echo '"'
} > generated/srcs.bzl

echo ""
echo "Setup complete. Generated files:"
echo "  File list:    generated/files.txt (${#FILES[@]} files)"
echo "  Include list: generated/includes.txt (${#INCLUDES[@]} dirs)"
echo "  Bazel srcs:   generated/srcs.bzl"
echo "  (FakeRAM via tools/regenerate_sram.sh; macros.v via dev/gen_macros_v.py)"
