#!/usr/bin/env python3
"""
Generate a Verilog blackbox stub for the Xilinx PCIe hard IP wrapper
("pcie_us" for UltraScale/UltraScale+, "pcie_s7" for 7-series) that
litepcie's `gen.py` instantiates.

The stub mirrors the port list (names + widths) seen in the generated
`litepcie_core.v` so yosys-slang accepts the instance without an
unresolved-port error, then declares the module `(* blackbox *)` so
OpenROAD treats it as a hard macro.  A matching LEF/LIB is still
required for placement.

Approach: parse the existing pcie_<X> instance from a generated
litepcie_core.v (post `gen.py` run), look up each connected signal's
declared width earlier in the file, and emit a stub with those ports.
This avoids hard-coding the (huge) port list and keeps the stub in
sync with whichever PHY variant was generated.
"""

import argparse
import re
import sys
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("verilog", help="Generated litepcie_core.v")
    ap.add_argument("--module", default="pcie_us",
                    help="PCIe hard-IP module name to stub (pcie_us, pcie_s7)")
    ap.add_argument("--out", required=True, help="Output Verilog stub path")
    args = ap.parse_args()

    text = Path(args.verilog).read_text()

    # ---- Find the target instance and its directionally-tagged ports. ----
    inst_re = re.compile(
        rf"^{re.escape(args.module)}\s+\w+\s*\(\s*\n(.*?)^\);",
        re.MULTILINE | re.DOTALL,
    )
    m = inst_re.search(text)
    if not m:
        sys.exit(f"could not find instance of module '{args.module}'")
    body = m.group(1)

    # Split the body into Inputs / Outputs sections (comments emitted by litex).
    in_part, _, out_part = body.partition("// Outputs.")
    if not out_part:
        sys.exit("instance body missing '// Outputs.' marker")

    port_re = re.compile(r"\.(\w+)\s*\(\s*([^)]*?)\s*\)")

    def parse_section(text):
        # litex emits each .port(net) on its own line; one match per port.
        return port_re.findall(text)

    in_ports  = parse_section(in_part)
    out_ports = parse_section(out_part)

    # ---- Build a width table from `wire [hi:lo] name;` declarations. ----
    wire_re = re.compile(
        r"^\s*(?:wire|reg)\s*(\[(\d+):(\d+)\])?\s+(\w+)\s*[=;]", re.MULTILINE
    )
    widths = {}
    for _, hi, lo, name in wire_re.findall(text):
        if hi:
            widths[name] = int(hi) - int(lo) + 1
        else:
            widths[name] = 1

    def width_of(connection):
        # Strip optional brace concat / bit-select; for tieoffs like 1'd0
        # the width can't be derived from the wire table — fall back to 1.
        # Tieoffs like "1'd0", "13'd4334": pick the literal width.
        m = re.match(r"^(\d+)'[dhbo]", connection)
        if m:
            return int(m.group(1))
        # Plain net name (possibly with [bit-range]):
        m = re.match(r"^(\w+)(?:\[\d+(?::\d+)?\])?$", connection)
        if m:
            return widths.get(m.group(1), 1)
        # Anything else (concat, math, ...): assume 1.
        return 1

    # ---- Emit the stub. ----
    out_lines = [
        "// SPDX-License-Identifier: BSD-2-Clause",
        f"// Blackbox stub for litepcie's '{args.module}' Xilinx PCIe hard-IP wrapper.",
        "// Auto-generated by designs/src/litepci/dev/gen_phy_stub.py — do not edit.",
        "//",
        "// litepcie's `gen.py` always instantiates a vendor PCIe hard IP at the",
        "// bottom of the design.  In an open ASIC flow we treat that block as an",
        "// off-chip macro: this stub declares the port list (so yosys-slang resolves",
        "// the instance) and the (* blackbox *) attribute keeps yosys from trying",
        "// to synthesize anything inside it.  A matching LEF is provided via",
        "// hightide_design()'s ADDITIONAL_LEFS so OpenROAD can place it.",
        "",
        "(* blackbox *)",
        f"module {args.module} (",
    ]

    decls = []
    seen = set()

    def add(direction, name, conn):
        if name in seen:
            return  # Duplicates shouldn't happen but guard anyway.
        seen.add(name)
        w = width_of(conn)
        if w == 1:
            decls.append(f"    {direction:<6} {name}")
        else:
            decls.append(f"    {direction:<6} [{w-1}:0] {name}")

    for name, conn in in_ports:
        add("input", name, conn)
    for name, conn in out_ports:
        add("output", name, conn)

    out_lines.append(",\n".join(decls))
    out_lines.append(");")
    out_lines.append("endmodule")
    out_lines.append("")

    Path(args.out).write_text("\n".join(out_lines))
    print(f"Wrote {args.out} ({len(in_ports)} in + {len(out_ports)} out ports)")


if __name__ == "__main__":
    main()
