# AUTO-GENERATED by tools/gen_macro_grid.py
# Fixed grid: every macro R0 (pins uniformly south), a routing
# channel below every row so each macro's met2 pin edge faces
# clear space. Macros FIRM so the post-source rtl_macro_placer
# leaves them alone. See the script header for the rationale.

place_macro -macro_name {u_storage_14_fakeram_1rw1r_130w1024d_sram} -location {51.380 202.720} -orientation R0
place_macro -macro_name {u_storage_8_fakeram_1rw1r_130w1024d_sram} -location {2516.240 202.720} -orientation R0
place_macro -macro_name {u_storage_10_fakeram_1rw1r_130w512d_sram} -location {51.380 2298.560} -orientation R0
place_macro -macro_name {u_storage_15_fakeram_1rw1r_130w512d_sram} -location {1334.040 2298.560} -orientation R0
place_macro -macro_name {u_storage_16_fakeram_1rw1r_130w512d_sram} -location {2616.700 2298.560} -orientation R0
place_macro -macro_name {u_storage_9_fakeram_1rw1r_130w512d_sram} -location {3899.360 2298.560} -orientation R0
place_macro -macro_name {pcie_us} -location {51.380 4394.400} -orientation R0
place_macro -macro_name {u_storage_19_fakeram_1rw1r_230w128d_sram} -location {51.380 5594.400} -orientation R0
place_macro -macro_name {u_storage_20_fakeram_1rw1r_230w128d_sram} -location {1197.420 5594.400} -orientation R0
place_macro -macro_name {u_storage_21_fakeram_1rw1r_230w128d_sram} -location {2343.460 5594.400} -orientation R0
place_macro -macro_name {u_storage_22_fakeram_1rw1r_230w128d_sram} -location {3489.500 5594.400} -orientation R0
place_macro -macro_name {u_storage_23_fakeram_1rw1r_230w128d_sram} -location {4635.540 5594.400} -orientation R0
place_macro -macro_name {u_storage_24_fakeram_1rw1r_230w128d_sram} -location {5781.580 5594.400} -orientation R0
place_macro -macro_name {u_storage_25_fakeram_1rw1r_230w128d_sram} -location {6927.620 5594.400} -orientation R0
place_macro -macro_name {u_storage_26_fakeram_1rw1r_230w128d_sram} -location {8073.660 5594.400} -orientation R0
place_macro -macro_name {u_storage_11_fakeram_1rw1r_92w256d_sram} -location {51.380 6743.680} -orientation R0
place_macro -macro_name {u_storage_13_fakeram_1rw1r_92w256d_sram} -location {988.580 6743.680} -orientation R0
place_macro -macro_name {u_storage_5_fakeram_1rw1r_92w256d_sram} -location {1925.780 6743.680} -orientation R0
place_macro -macro_name {u_storage_7_fakeram_1rw1r_92w256d_sram} -location {2862.980 6743.680} -orientation R0
place_macro -macro_name {u_storage_12_fakeram_1rw1r_130w128d_sram} -location {51.380 7892.960} -orientation R0
place_macro -macro_name {u_storage_6_fakeram_1rw1r_130w128d_sram} -location {742.940 7892.960} -orientation R0

set _blk [ord::get_db_block]
foreach _m {
  {pcie_us}
  {u_storage_10_fakeram_1rw1r_130w512d_sram}
  {u_storage_11_fakeram_1rw1r_92w256d_sram}
  {u_storage_12_fakeram_1rw1r_130w128d_sram}
  {u_storage_13_fakeram_1rw1r_92w256d_sram}
  {u_storage_14_fakeram_1rw1r_130w1024d_sram}
  {u_storage_15_fakeram_1rw1r_130w512d_sram}
  {u_storage_16_fakeram_1rw1r_130w512d_sram}
  {u_storage_19_fakeram_1rw1r_230w128d_sram}
  {u_storage_20_fakeram_1rw1r_230w128d_sram}
  {u_storage_21_fakeram_1rw1r_230w128d_sram}
  {u_storage_22_fakeram_1rw1r_230w128d_sram}
  {u_storage_23_fakeram_1rw1r_230w128d_sram}
  {u_storage_24_fakeram_1rw1r_230w128d_sram}
  {u_storage_25_fakeram_1rw1r_230w128d_sram}
  {u_storage_26_fakeram_1rw1r_230w128d_sram}
  {u_storage_5_fakeram_1rw1r_92w256d_sram}
  {u_storage_6_fakeram_1rw1r_130w128d_sram}
  {u_storage_7_fakeram_1rw1r_92w256d_sram}
  {u_storage_8_fakeram_1rw1r_130w1024d_sram}
  {u_storage_9_fakeram_1rw1r_130w512d_sram}
} {
  set _i [$_blk findInst $_m]
  if {$_i ne "NULL" && $_i ne ""} { $_i setPlacementStatus FIRM }
}

