// Auto-generated FakeRAM-backed bsg_mem_*_synth replacements.
// Large memories (>= 1024 bits) use FakeRAM macros.
// Small memories fall back to register-array implementation.
//
// Generated by gen_fakeram.py — do not edit manually.

module bsg_mem_1rw_sync_synth (
	clk_i,
	v_i,
	reset_i,
	data_i,
	addr_i,
	w_i,
	data_o
);
	parameter width_p = 0;
	parameter els_p = 0;
	parameter latch_last_read_p = 0;
	parameter addr_width_lp = ((els_p == 1) || (els_p == 0) ? 1 : $clog2(els_p));
	parameter verbose_p = 1;
	input clk_i;
	input v_i;
	input reset_i;
	input [(width_p < 1 ? 0 : width_p - 1):0] data_i;
	input [addr_width_lp - 1:0] addr_i;
	input w_i;
	output wire [(width_p < 1 ? 0 : width_p - 1):0] data_o;
	wire unused = reset_i;
	generate
		if ((width_p == 0) || (els_p == 0)) begin : z
			wire unused0 = &{clk_i, v_i, data_i, addr_i, w_i};
			assign data_o = 1'sb0;
		end
		else if ((els_p == 512) && (width_p == 64)) begin : fakeram_512x64
			fakeram_512x64_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in({64{w_i}}),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else if ((els_p == 64) && (width_p == 184)) begin : fakeram_64x184
			fakeram_64x184_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in({184{w_i}}),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else if ((els_p == 512) && (width_p == 8)) begin : fakeram_512x8
			fakeram_512x8_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in({8{w_i}}),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else if ((els_p == 64) && (width_p == 50)) begin : fakeram_64x50
			fakeram_64x50_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in({50{w_i}}),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else if ((els_p == 32) && (width_p == 66)) begin : fakeram_32x66
			fakeram_32x66_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in({66{w_i}}),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else if ((els_p == 32) && (width_p == 48)) begin : fakeram_32x48
			fakeram_32x48_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in({48{w_i}}),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else if ((els_p == 8) && (width_p == 174)) begin : fakeram_8x174
			fakeram_8x174_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in({174{w_i}}),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else if ((els_p == 128) && (width_p == 8)) begin : fakeram_128x8
			fakeram_128x8_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in({8{w_i}}),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else begin : nz
			reg [addr_width_lp - 1:0] addr_r;
			reg [width_p - 1:0] mem [els_p - 1:0];
			wire read_en;
			wire [width_p - 1:0] data_out;
			wire [addr_width_lp - 1:0] addr_li = (els_p > 0 ? addr_i : {addr_width_lp {1'sb0}});
			assign read_en = v_i & ~w_i;
			assign data_out = mem[addr_r];
			always @(posedge clk_i)
				if (read_en)
					addr_r <= addr_li;
				else
					addr_r <= 1'sbx;
			if (latch_last_read_p) begin : llr
				wire read_en_r;
				bsg_dff #(.width_p(1)) read_en_dff(
					.clk_i(clk_i),
					.data_i(read_en),
					.data_o(read_en_r)
				);
				bsg_dff_en_bypass #(.width_p(width_p)) dff_bypass(
					.clk_i(clk_i),
					.en_i(read_en_r),
					.data_i(data_out),
					.data_o(data_o)
				);
			end
			else begin : no_llr
				assign data_o = data_out;
			end
			always @(posedge clk_i)
				if (v_i & w_i)
					mem[addr_li] <= data_i;
		end
	endgenerate
endmodule

module bsg_mem_1rw_sync_mask_write_bit_synth (
	clk_i,
	reset_i,
	data_i,
	addr_i,
	v_i,
	w_mask_i,
	w_i,
	data_o
);
	parameter width_p = 0;
	parameter els_p = 0;
	parameter latch_last_read_p = 0;
	parameter addr_width_lp = ((els_p == 1) || (els_p == 0) ? 1 : $clog2(els_p));
	input clk_i;
	input reset_i;
	input [(width_p < 1 ? 0 : width_p - 1):0] data_i;
	input [addr_width_lp - 1:0] addr_i;
	input v_i;
	input [(width_p < 1 ? 0 : width_p - 1):0] w_mask_i;
	input w_i;
	output wire [(width_p < 1 ? 0 : width_p - 1):0] data_o;
	wire unused = reset_i;
	generate
		if ((width_p == 0) || (els_p == 0)) begin : z
			wire unused0 = &{clk_i, data_i, addr_i, v_i, w_mask_i, w_i};
			assign data_o = 1'sb0;
		end
		else if ((els_p == 512) && (width_p == 64)) begin : fakeram_512x64
			fakeram_512x64_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in(w_mask_i),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else if ((els_p == 64) && (width_p == 184)) begin : fakeram_64x184
			fakeram_64x184_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in(w_mask_i),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else if ((els_p == 512) && (width_p == 8)) begin : fakeram_512x8
			fakeram_512x8_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in(w_mask_i),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else if ((els_p == 64) && (width_p == 50)) begin : fakeram_64x50
			fakeram_64x50_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in(w_mask_i),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else if ((els_p == 32) && (width_p == 66)) begin : fakeram_32x66
			fakeram_32x66_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in(w_mask_i),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else if ((els_p == 32) && (width_p == 48)) begin : fakeram_32x48
			fakeram_32x48_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in(w_mask_i),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else if ((els_p == 8) && (width_p == 174)) begin : fakeram_8x174
			fakeram_8x174_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in(w_mask_i),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else if ((els_p == 128) && (width_p == 8)) begin : fakeram_128x8
			fakeram_128x8_1rw mem (
				.clk(clk_i),
				.ce_in(v_i),
				.we_in(w_i),
				.w_mask_in(w_mask_i),
				.addr_in(addr_i),
				.wd_in(data_i),
				.rd_out(data_o)
			);
		end
		else begin : nz
			reg [addr_width_lp - 1:0] addr_r;
			reg [width_p - 1:0] mem [els_p - 1:0];
			wire read_en;
			wire [addr_width_lp - 1:0] addr_li = (els_p > 1 ? addr_i : {addr_width_lp {1'sb0}});
			assign read_en = v_i & ~w_i;
			always @(posedge clk_i)
				if (read_en)
					addr_r <= addr_li;
				else
					addr_r <= 1'sbx;
			wire [width_p - 1:0] data_out;
			assign data_out = mem[addr_r];
			if (latch_last_read_p) begin : llr
				wire read_en_r;
				bsg_dff #(.width_p(1)) read_en_dff(
					.clk_i(clk_i),
					.data_i(read_en),
					.data_o(read_en_r)
				);
				bsg_dff_en_bypass #(.width_p(width_p)) dff_bypass(
					.clk_i(clk_i),
					.en_i(read_en_r),
					.data_i(data_out),
					.data_o(data_o)
				);
			end
			else begin : no_llr
				assign data_o = data_out;
			end
			always @(posedge clk_i)
				if (v_i & w_i) begin : sv2v_autoblock_1
					integer i;
					for (i = 0; i < width_p; i = i + 1)
						if (w_mask_i[i])
							mem[addr_li][i] <= data_i[i];
				end
		end
	endgenerate
endmodule

