#!/usr/bin/env bash
#
# Launch OpenROAD GUI on a stage ODB with full timing setup (Liberty
# libs, SDC, RC corner). Invoked by per-stage <design>_gui_<stage>
# sh_binary targets generated by hightide_design().
#
# Bypasses ORFS's `make gui_<stage>` interface — instead we manually
# load liberty files, the ODB, the SDC, and the platform setRC.tcl
# before dropping into the OpenROAD GUI shell.
#
# Args (positional, set by the sh_binary):
#   $1   workspace-relative path of the openroad binary
#   $2   workspace-relative path of the open_db.tcl script

set -eu

OPENROAD="$1"
TCL="$2"

# $(rootpath) make-vars are relative to the workspace dir _within_ the
# runfiles tree (i.e. RUNFILES/_main); chdir there so external-repo
# refs like `../openroad+/openroad` resolve.
RUNFILES="${RUNFILES_DIR:-$0.runfiles}"
if [ ! -d "$RUNFILES/_main" ]; then
    echo "Error: runfiles _main dir not found: $RUNFILES/_main" >&2
    exit 1
fi
cd "$RUNFILES/_main"

OPENROAD_ABS="$(realpath "$OPENROAD")"
TCL_ABS="$(realpath "$TCL")"

# Locate the stage ODB anywhere under the runfiles tree (orfs stage
# targets produce exactly one ODB per stage). SDC matches the ODB stem.
ODB="$(find -L . -type f -name '*.odb' -print -quit 2>/dev/null || true)"
if [ -z "$ODB" ]; then
    echo "Error: no .odb found in runfiles tree at $(pwd)" >&2
    exit 1
fi
ODB_ABS="$(realpath "$ODB")"

SDC="${ODB%.odb}.sdc"
SDC_ABS=""
if [ -f "$SDC" ]; then
    SDC_ABS="$(realpath "$SDC")"
fi

# Read PLATFORM from the stage's short.mk (orfs writes
# `export PLATFORM?=<plat>`). Drives the setRC + Liberty paths.
SHORTMK="$(find -L . -type f -name '*.short.mk' -print -quit 2>/dev/null || true)"
PLATFORM=""
if [ -n "$SHORTMK" ]; then
    PLATFORM="$(awk -F'?=' '/^export PLATFORM\?=/{print $2; exit}' "$SHORTMK")"
fi
if [ -z "$PLATFORM" ]; then
    echo "Error: could not determine PLATFORM from short.mk" >&2
    exit 1
fi
PLATFORM_DIR_ABS="$(realpath "$RUNFILES/orfs+/flow/platforms/$PLATFORM")"

# Liberty files: platform libs + any design-specific *.lib(.gz) in the
# runfiles tree (e.g. FakeRAM SRAMs). Dedupe by realpath to avoid
# re-reading the same file from multiple symlinks.
declare -A seen
LIB_LIST=""
while IFS= read -r f; do
    abs="$(realpath "$f")"
    if [ -z "${seen[$abs]:-}" ]; then
        seen[$abs]=1
        LIB_LIST="${LIB_LIST}:${abs}"
    fi
done < <(find -L "$PLATFORM_DIR_ABS/lib" . -type f \( -name '*.lib' -o -name '*.lib.gz' \) 2>/dev/null)

export ODB_FILE="$ODB_ABS"
[ -n "$SDC_ABS" ] && export SDC_FILE="$SDC_ABS"
export PLATFORM_DIR="$PLATFORM_DIR_ABS"
export LIB_FILES_LIST="${LIB_LIST#:}"

echo "Launching OpenROAD GUI"
echo "  ODB:      $ODB_ABS"
[ -n "$SDC_ABS" ] && echo "  SDC:      $SDC_ABS"
echo "  Platform: $PLATFORM ($PLATFORM_DIR_ABS)"

exec "$OPENROAD_ABS" -gui -no_init "$TCL_ABS"
