# AUTO-GENERATED by tools/gen_macro_grid.py
# Fixed grid: alternating R0/MX, a routing
# channel below every row so each macro's met2 pin edge faces
# clear space. Macros FIRM so the post-source rtl_macro_placer
# leaves them alone. See the script header for the rationale.

place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {400.050 788.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {1830.890 788.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3261.730 788.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {4692.570 788.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {6123.410 788.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7554.250 788.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {8985.090 788.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {10415.930 788.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {400.050 1953.680} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {1830.890 1953.680} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3261.730 1953.680} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {4692.570 1953.680} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {6123.410 1953.680} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7554.250 1953.680} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {8985.090 1953.680} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {10415.930 1953.680} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {400.050 3368.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {1830.890 3368.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3261.730 3368.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {4692.570 3368.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {6123.410 3368.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7554.250 3368.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {8985.090 3368.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {10415.930 3368.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {400.050 4533.600} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {1830.890 4533.600} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3261.730 4533.600} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {4692.570 4533.600} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {6123.410 4533.600} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7554.250 4533.600} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {8985.090 4533.600} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {10415.930 4533.600} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {400.050 5948.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {1830.890 5948.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3261.730 5948.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {4692.570 5948.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {6123.410 5948.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7554.250 5948.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {8985.090 5948.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {10415.930 5948.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {400.050 7113.520} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {1830.890 7113.520} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3261.730 7113.520} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {4692.570 7113.520} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {6123.410 7113.520} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7554.250 7113.520} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {8985.090 7113.520} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {10415.930 7113.520} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {400.050 8528.480} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {1830.890 8528.480} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3261.730 8528.480} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {4692.570 8528.480} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {6123.410 8528.480} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7554.250 8528.480} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {8985.090 8528.480} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {10415.930 8528.480} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {400.050 9693.440} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {1830.890 9693.440} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3261.730 9693.440} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {4692.570 9693.440} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {6123.410 9693.440} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7554.250 9693.440} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {8985.090 9693.440} -orientation MX
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {10415.930 9693.440} -orientation MX

# aside macros — left side corridor, vertically centred
place_macro -macro_name {u_NV_NVDLA_cdma/u_img/u_sg/u_NV_NVDLA_CDMA_IMG_fifo/ram/r_nv_ram_rwsp_128x11/ram_Inst_128X11/sram} -location {109.405 5565.120} -orientation R0

set _blk [ord::get_db_block]
foreach _m {
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cdma/u_img/u_sg/u_NV_NVDLA_CDMA_IMG_fifo/ram/r_nv_ram_rwsp_128x11/ram_Inst_128X11/sram}
} {
  set _i [$_blk findInst $_m]
  if {$_i ne "NULL" && $_i ne ""} { $_i setPlacementStatus FIRM }
}

