# AUTO-GENERATED by tools/gen_macro_grid.py
# Fixed grid: every macro R0 (pins uniformly south), a routing
# channel below every row so each macro's met2 pin edge faces
# clear space. Macros FIRM so the post-source rtl_macro_placer
# leaves them alone. See the script header for the rationale.

place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {51.380 452.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {832.220 452.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {1613.060 452.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {2393.900 452.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3174.740 452.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3955.580 452.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {4736.420 452.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {5517.260 452.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {6298.100 452.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7078.940 452.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7859.780 452.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {8640.620 452.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {9421.460 452.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {10202.300 452.720} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {51.380 1767.680} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {832.220 1767.680} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {1613.060 1767.680} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {2393.900 1767.680} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3174.740 1767.680} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3955.580 1767.680} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {4736.420 1767.680} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {5517.260 1767.680} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {6298.100 1767.680} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7078.940 1767.680} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7859.780 1767.680} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {8640.620 1767.680} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {9421.460 1767.680} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {10202.300 1767.680} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {51.380 3082.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {832.220 3082.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {1613.060 3082.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {2393.900 3082.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3174.740 3082.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3955.580 3082.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {4736.420 3082.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {5517.260 3082.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {6298.100 3082.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7078.940 3082.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7859.780 3082.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {8640.620 3082.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {9421.460 3082.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {10202.300 3082.640} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {51.380 4397.600} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {832.220 4397.600} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {1613.060 4397.600} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {2393.900 4397.600} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3174.740 4397.600} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3955.580 4397.600} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {4736.420 4397.600} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {5517.260 4397.600} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {6298.100 4397.600} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7078.940 4397.600} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {7859.780 4397.600} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {8640.620 4397.600} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {9421.460 4397.600} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {10202.300 4397.600} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {51.380 5712.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {832.220 5712.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {1613.060 5712.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {2393.900 5712.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3174.740 5712.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {3955.580 5712.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {4736.420 5712.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram} -location {5517.260 5712.560} -orientation R0
place_macro -macro_name {u_NV_NVDLA_cdma/u_img/u_sg/u_NV_NVDLA_CDMA_IMG_fifo/ram/r_nv_ram_rwsp_128x11/ram_Inst_128X11/sram} -location {51.380 7027.520} -orientation R0

set _blk [ord::get_db_block]
foreach _m {
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank10_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank11_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank12_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank13_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank14_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank15_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank16_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank17_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank18_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank19_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank1_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank20_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank21_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank22_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank23_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank24_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank25_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank26_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank27_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank28_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank29_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank2_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank30_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank31_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank3_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank4_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank5_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank6_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank7_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank8_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram0/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cbuf/u_cbuf_ram_bank9_ram1/r_nv_ram_rws_256x64/ram_Inst_256X64/sram}
  {u_NV_NVDLA_cdma/u_img/u_sg/u_NV_NVDLA_CDMA_IMG_fifo/ram/r_nv_ram_rwsp_128x11/ram_Inst_128X11/sram}
} {
  set _i [$_blk findInst $_m]
  if {$_i ne "NULL" && $_i ne ""} { $_i setPlacementStatus FIRM }
}

