// Auto-generated by designs/src/bp_processor/dev/gen_macros_v.py — do not edit.
//
// Large memories (listed below) bind to bsg_fakeram-generated
// fakeram_DxW_1rw macros via the rw0_* pin convention. Everything else
// falls through to a behavioural register array (synthesises to FFs).

module bsg_mem_1rw_sync_synth (
	clk_i,
	v_i,
	reset_i,
	data_i,
	addr_i,
	w_i,
	data_o
);
	parameter width_p = 0;
	parameter els_p = 0;
	parameter latch_last_read_p = 0;
	parameter addr_width_lp = ((els_p == 1) || (els_p == 0) ? 1 : $clog2(els_p));
	parameter verbose_p = 1;
	input clk_i;
	input v_i;
	input reset_i;
	input [(width_p < 1 ? 0 : width_p - 1):0] data_i;
	input [addr_width_lp - 1:0] addr_i;
	input w_i;
	output wire [(width_p < 1 ? 0 : width_p - 1):0] data_o;
	wire unused = reset_i;
	generate
		if ((width_p == 0) || (els_p == 0)) begin : z
			wire unused0 = &{clk_i, v_i, data_i, addr_i, w_i};
			assign data_o = 1'sb0;
		end
		else if ((els_p == 512) && (width_p == 64)) begin : fakeram_512x64
			fakeram_512x64_1rw mem (
				.rw0_clk(clk_i),
				.rw0_ce_in(v_i),
				.rw0_we_in(w_i),
				.rw0_wmask_in({64{w_i}}),
				.rw0_addr_in(addr_i),
				.rw0_wd_in(data_i),
				.rw0_rd_out(data_o)
			);
		end
		else if ((els_p == 64) && (width_p == 184)) begin : fakeram_64x184
			fakeram_64x184_1rw mem (
				.rw0_clk(clk_i),
				.rw0_ce_in(v_i),
				.rw0_we_in(w_i),
				.rw0_wmask_in({184{w_i}}),
				.rw0_addr_in(addr_i),
				.rw0_wd_in(data_i),
				.rw0_rd_out(data_o)
			);
		end
		else if ((els_p == 512) && (width_p == 8)) begin : fakeram_512x8
			fakeram_512x8_1rw mem (
				.rw0_clk(clk_i),
				.rw0_ce_in(v_i),
				.rw0_we_in(w_i),
				.rw0_wmask_in({8{w_i}}),
				.rw0_addr_in(addr_i),
				.rw0_wd_in(data_i),
				.rw0_rd_out(data_o)
			);
		end
		else if ((els_p == 64) && (width_p == 50)) begin : fakeram_64x50
			fakeram_64x50_1rw mem (
				.rw0_clk(clk_i),
				.rw0_ce_in(v_i),
				.rw0_we_in(w_i),
				.rw0_wmask_in({50{w_i}}),
				.rw0_addr_in(addr_i),
				.rw0_wd_in(data_i),
				.rw0_rd_out(data_o)
			);
		end
		else if ((els_p == 32) && (width_p == 48)) begin : fakeram_32x48
			fakeram_32x48_1rw mem (
				.rw0_clk(clk_i),
				.rw0_ce_in(v_i),
				.rw0_we_in(w_i),
				.rw0_wmask_in({48{w_i}}),
				.rw0_addr_in(addr_i),
				.rw0_wd_in(data_i),
				.rw0_rd_out(data_o)
			);
		end
		else if ((els_p == 128) && (width_p == 8)) begin : fakeram_128x8
			fakeram_128x8_1rw mem (
				.rw0_clk(clk_i),
				.rw0_ce_in(v_i),
				.rw0_we_in(w_i),
				.rw0_wmask_in({8{w_i}}),
				.rw0_addr_in(addr_i),
				.rw0_wd_in(data_i),
				.rw0_rd_out(data_o)
			);
		end
		else begin : nz
			reg [addr_width_lp - 1:0] addr_r;
			reg [width_p - 1:0] mem [els_p - 1:0];
			wire read_en;
			wire [width_p - 1:0] data_out;
			wire [addr_width_lp - 1:0] addr_li = (els_p > 0 ? addr_i : {addr_width_lp {1'sb0}});
			assign read_en = v_i & ~w_i;
			assign data_out = mem[addr_r];
			always @(posedge clk_i)
				if (read_en)
					addr_r <= addr_li;
				else
					addr_r <= 1'sbx;
			assign data_o = data_out;
			always @(posedge clk_i)
				if (v_i & w_i)
					mem[addr_li] <= data_i;
		end
	endgenerate
endmodule

module bsg_mem_1rw_sync_mask_write_bit_synth (
	clk_i,
	reset_i,
	data_i,
	addr_i,
	v_i,
	w_mask_i,
	w_i,
	data_o
);
	parameter width_p = 0;
	parameter els_p = 0;
	parameter latch_last_read_p = 0;
	parameter addr_width_lp = ((els_p == 1) || (els_p == 0) ? 1 : $clog2(els_p));
	parameter verbose_p = 1;
	input clk_i;
	input reset_i;
	input [(width_p < 1 ? 0 : width_p - 1):0] data_i;
	input [addr_width_lp - 1:0] addr_i;
	input v_i;
	input [(width_p < 1 ? 0 : width_p - 1):0] w_mask_i;
	input w_i;
	output wire [(width_p < 1 ? 0 : width_p - 1):0] data_o;
	wire unused = reset_i;
	generate
		if ((width_p == 0) || (els_p == 0)) begin : z
			wire unused0 = &{clk_i, data_i, addr_i, v_i, w_mask_i, w_i};
			assign data_o = 1'sb0;
		end
		else if ((els_p == 512) && (width_p == 64)) begin : fakeram_512x64
			fakeram_512x64_1rw mem (
				.rw0_clk(clk_i),
				.rw0_ce_in(v_i),
				.rw0_we_in(w_i),
				.rw0_wmask_in(w_mask_i),
				.rw0_addr_in(addr_i),
				.rw0_wd_in(data_i),
				.rw0_rd_out(data_o)
			);
		end
		else if ((els_p == 64) && (width_p == 184)) begin : fakeram_64x184
			fakeram_64x184_1rw mem (
				.rw0_clk(clk_i),
				.rw0_ce_in(v_i),
				.rw0_we_in(w_i),
				.rw0_wmask_in(w_mask_i),
				.rw0_addr_in(addr_i),
				.rw0_wd_in(data_i),
				.rw0_rd_out(data_o)
			);
		end
		else if ((els_p == 512) && (width_p == 8)) begin : fakeram_512x8
			fakeram_512x8_1rw mem (
				.rw0_clk(clk_i),
				.rw0_ce_in(v_i),
				.rw0_we_in(w_i),
				.rw0_wmask_in(w_mask_i),
				.rw0_addr_in(addr_i),
				.rw0_wd_in(data_i),
				.rw0_rd_out(data_o)
			);
		end
		else if ((els_p == 64) && (width_p == 50)) begin : fakeram_64x50
			fakeram_64x50_1rw mem (
				.rw0_clk(clk_i),
				.rw0_ce_in(v_i),
				.rw0_we_in(w_i),
				.rw0_wmask_in(w_mask_i),
				.rw0_addr_in(addr_i),
				.rw0_wd_in(data_i),
				.rw0_rd_out(data_o)
			);
		end
		else if ((els_p == 32) && (width_p == 48)) begin : fakeram_32x48
			fakeram_32x48_1rw mem (
				.rw0_clk(clk_i),
				.rw0_ce_in(v_i),
				.rw0_we_in(w_i),
				.rw0_wmask_in(w_mask_i),
				.rw0_addr_in(addr_i),
				.rw0_wd_in(data_i),
				.rw0_rd_out(data_o)
			);
		end
		else if ((els_p == 128) && (width_p == 8)) begin : fakeram_128x8
			fakeram_128x8_1rw mem (
				.rw0_clk(clk_i),
				.rw0_ce_in(v_i),
				.rw0_we_in(w_i),
				.rw0_wmask_in(w_mask_i),
				.rw0_addr_in(addr_i),
				.rw0_wd_in(data_i),
				.rw0_rd_out(data_o)
			);
		end
		else begin : nz
			reg [addr_width_lp - 1:0] addr_r;
			reg [width_p - 1:0] mem [els_p - 1:0];
			wire read_en;
			wire [width_p - 1:0] data_out;
			wire [addr_width_lp - 1:0] addr_li = (els_p > 0 ? addr_i : {addr_width_lp {1'sb0}});
			assign read_en = v_i & ~w_i;
			assign data_out = mem[addr_r];
			always @(posedge clk_i)
				if (read_en)
					addr_r <= addr_li;
				else
					addr_r <= 1'sbx;
			assign data_o = data_out;
			always @(posedge clk_i)
				if (v_i & w_i)
					mem[addr_li] <= data_i;
		end
	endgenerate
endmodule
