#!/usr/bin/env python3
"""Generate a fixed-grid MACRO_PLACEMENT_TCL for cnn / sky130hd.

Why this exists
---------------
With the wd_in-fixed bsg_fakeram LEFs, cnn-sky130hd's GRT solves at only
2.06% global routing usage yet fails with ~1743 *vertical* capacity:0
overflow concentrated entirely on met2.  Every fakeram macro places all
of its signal pins on its bottom edge on met2.  RTLMP is pin-edge-blind
and packs the 65 macros with mixed orientations (MX/R180 flip the pin
edge to the top), so adjacent macros' pin edges abut with zero routing
space between them -> localized met2 zero-capacity seams.

This emits a regular grid: every macro forced to R0 (pins all face the
same way, south) and a generous routing channel below every row so each
macro's met2 pin edge always faces routable space, never another macro.
Macros are set FIRM so the rtl_macro_placer that ORFS runs *after*
sourcing MACRO_PLACEMENT_TCL leaves them alone.

Source of truth for the 65 instance names + sizes is the committed LEF
set + the elaborated netlist; we read them from a one-time ODB dump
(tools/dump pattern) checked in as dev/generated/cnn_sky130hd_macros.txt
so this script has no ODB dependency at run time.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DUMP = os.path.join(HERE, "generated", "cnn_sky130hd_macros.txt")

# Core (um) from the 2_floorplan ODB: 5.06 5.44 19994.82 19994.72
CORE_X0, CORE_Y0, CORE_X1, CORE_Y1 = 5.06, 5.44, 19994.82, 19994.72
MARGIN = 50.0          # keep macros off the core edge
GAP_X = 200.0          # horizontal gap between macros in a row
CH_BIG = 450.0         # channel below a row of large macros
CH_SML = 350.0         # channel below a row of small macros

# size -> (w, h); kept here only for row packing math
SIZES = {
    "fakeram_w16_l32768": (4930.74, 4009.28),
    "fakeram_w16_l8192":  (2465.60, 2004.64),
    "fakeram_w64_l256":   (616.40, 1003.68),
    "fakeram_w16_l512":   (616.40,  503.20),
}


def load_macros(path):
    macros = []  # (inst, master, w, h)
    with open(path) as f:
        for line in f:
            if not line.startswith("MACRO"):
                continue
            # MACRO <inst> | <master> | <orient> | x y | WxH | status
            parts = [p.strip() for p in line[5:].split("|")]
            inst, master = parts[0], parts[1]
            w, h = SIZES[master]
            macros.append((inst, master, w, h))
    return macros


def pack_rows(macros, x0, x_limit):
    """Group like-sized macros into left-aligned rows that fit x_limit."""
    by_master = {}
    for m in macros:
        by_master.setdefault(m[1], []).append(m)
    # Largest first so the tall rows sit at the bottom.
    order = ["fakeram_w16_l32768", "fakeram_w16_l8192",
             "fakeram_w64_l256", "fakeram_w16_l512"]
    rows = []
    for master in order:
        group = by_master.get(master, [])
        if not group:
            continue
        w = group[0][2]
        per_row = max(1, int((x_limit - x0 + GAP_X) // (w + GAP_X)))
        for i in range(0, len(group), per_row):
            rows.append(group[i:i + per_row])
    return rows


def main():
    if not os.path.exists(DUMP):
        sys.exit(f"missing {DUMP} (regenerate via the dump_macros.tcl step)")
    macros = load_macros(DUMP)
    assert len(macros) == 65, f"expected 65 macros, got {len(macros)}"

    x0 = CORE_X0 + MARGIN
    x_limit = CORE_X1 - MARGIN
    rows = pack_rows(macros, x0, x_limit)

    out = []
    out.append("# AUTO-GENERATED by designs/src/cnn/dev/gen_macro_grid_sky130hd.py")
    out.append("# Fixed-grid macro placement for cnn/sky130hd: all macros R0,")
    out.append("# wide channel below every row so each macro's met2 pin edge")
    out.append("# (bottom) always faces routable space.  See the script header.")
    out.append("")

    # Start one full channel up so row 1's south (met2-pin) edge also
    # faces a routing channel, not the core boundary.
    y = CORE_Y0 + CH_BIG
    for row in rows:
        rh = row[0][3]
        big = row[0][1] == "fakeram_w16_l32768" or row[0][1] == "fakeram_w16_l8192"
        x = x0
        for inst, master, w, h in row:
            out.append(
                f"place_macro -macro_name {{{inst}}} "
                f"-location {{{x:.3f} {y:.3f}}} -orientation R0")
            x += w + GAP_X
        y += rh + (CH_BIG if big else CH_SML)

    top = y - (CH_BIG if rows and rows[-1][0][1].startswith("fakeram_w16_l3") else CH_SML)
    assert top < CORE_Y1 - MARGIN, f"grid overflows core: top={top:.1f}"

    # Pin the macros so the rtl_macro_placer ORFS runs afterwards skips them.
    out.append("")
    out.append("set _blk [ord::get_db_block]")
    out.append("foreach _m {")
    for inst, *_ in macros:
        out.append(f"  {{{inst}}}")
    out.append("} {")
    out.append("  set _i [$_blk findInst $_m]")
    out.append("  if {$_i ne \"NULL\" && $_i ne \"\"} { $_i setPlacementStatus FIRM }")
    out.append("}")
    out.append("")

    # HERE=designs/src/cnn/dev -> repo root is four dirnames up.
    repo_root = HERE
    for _ in range(4):
        repo_root = os.path.dirname(repo_root)
    dst = os.path.join(repo_root, "designs", "sky130hd", "cnn",
                        "macro_placement.tcl")
    with open(dst, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {dst}")
    print(f"rows={len(rows)} macros={len(macros)} grid_top={top:.1f}um "
          f"(core_y1={CORE_Y1})")


if __name__ == "__main__":
    main()
