# AUTO-GENERATED by designs/src/cnn/dev/gen_macro_grid_sky130hd.py
# Fixed-grid macro placement for cnn/sky130hd: all macros R0,
# wide channel below every row so each macro's met2 pin edge
# (bottom) always faces routable space.  See the script header.

place_macro -macro_name {inst_ram_w16_l32768_id0_0/u_ram_w16_l32768_id0_0_mem} -location {55.060 455.440} -orientation R0
place_macro -macro_name {inst_ram_w16_l32768_id0_1/u_ram_w16_l32768_id0_1_mem} -location {5185.800 455.440} -orientation R0
place_macro -macro_name {inst_ram_w16_l32768_id1_0/u_ram_w16_l32768_id1_0_mem} -location {10316.540 455.440} -orientation R0
place_macro -macro_name {inst_ram_w16_l32768_id1_1/u_ram_w16_l32768_id1_1_mem} -location {55.060 4914.720} -orientation R0
place_macro -macro_name {inst_ram_w16_l8192_id0_0/u_ram_w16_l8192_id0_0_mem} -location {55.060 9374.000} -orientation R0
place_macro -macro_name {inst_ram_w16_l8192_id0_1/u_ram_w16_l8192_id0_1_mem} -location {2720.660 9374.000} -orientation R0
place_macro -macro_name {inst_ram_w64_l256_id0/u_ram_w64_l256_id0_mem} -location {55.060 11828.640} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id0_0/u_ram_w16_l512_id0_0_mem} -location {55.060 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id0_1/u_ram_w16_l512_id0_1_mem} -location {871.460 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id10_0/u_ram_w16_l512_id10_0_mem} -location {1687.860 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id10_1/u_ram_w16_l512_id10_1_mem} -location {2504.260 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id11_0/u_ram_w16_l512_id11_0_mem} -location {3320.660 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id11_1/u_ram_w16_l512_id11_1_mem} -location {4137.060 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id12_0/u_ram_w16_l512_id12_0_mem} -location {4953.460 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id12_1/u_ram_w16_l512_id12_1_mem} -location {5769.860 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id13_0/u_ram_w16_l512_id13_0_mem} -location {6586.260 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id13_1/u_ram_w16_l512_id13_1_mem} -location {7402.660 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id14_0/u_ram_w16_l512_id14_0_mem} -location {8219.060 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id14_1/u_ram_w16_l512_id14_1_mem} -location {9035.460 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id15_0/u_ram_w16_l512_id15_0_mem} -location {9851.860 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id15_1/u_ram_w16_l512_id15_1_mem} -location {10668.260 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id16_0/u_ram_w16_l512_id16_0_mem} -location {11484.660 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id16_1/u_ram_w16_l512_id16_1_mem} -location {12301.060 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id17_0/u_ram_w16_l512_id17_0_mem} -location {13117.460 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id17_1/u_ram_w16_l512_id17_1_mem} -location {13933.860 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id18_0/u_ram_w16_l512_id18_0_mem} -location {14750.260 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id18_1/u_ram_w16_l512_id18_1_mem} -location {15566.660 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id19_0/u_ram_w16_l512_id19_0_mem} -location {16383.060 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id19_1/u_ram_w16_l512_id19_1_mem} -location {17199.460 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id1_0/u_ram_w16_l512_id1_0_mem} -location {18015.860 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id1_1/u_ram_w16_l512_id1_1_mem} -location {18832.260 13182.320} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id20_0/u_ram_w16_l512_id20_0_mem} -location {55.060 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id20_1/u_ram_w16_l512_id20_1_mem} -location {871.460 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id21_0/u_ram_w16_l512_id21_0_mem} -location {1687.860 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id21_1/u_ram_w16_l512_id21_1_mem} -location {2504.260 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id22_0/u_ram_w16_l512_id22_0_mem} -location {3320.660 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id22_1/u_ram_w16_l512_id22_1_mem} -location {4137.060 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id23_0/u_ram_w16_l512_id23_0_mem} -location {4953.460 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id23_1/u_ram_w16_l512_id23_1_mem} -location {5769.860 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id24_0/u_ram_w16_l512_id24_0_mem} -location {6586.260 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id24_1/u_ram_w16_l512_id24_1_mem} -location {7402.660 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id25_0/u_ram_w16_l512_id25_0_mem} -location {8219.060 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id25_1/u_ram_w16_l512_id25_1_mem} -location {9035.460 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id26_0/u_ram_w16_l512_id26_0_mem} -location {9851.860 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id26_1/u_ram_w16_l512_id26_1_mem} -location {10668.260 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id27_0/u_ram_w16_l512_id27_0_mem} -location {11484.660 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id27_1/u_ram_w16_l512_id27_1_mem} -location {12301.060 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id28_0/u_ram_w16_l512_id28_0_mem} -location {13117.460 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id28_1/u_ram_w16_l512_id28_1_mem} -location {13933.860 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id2_0/u_ram_w16_l512_id2_0_mem} -location {14750.260 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id2_1/u_ram_w16_l512_id2_1_mem} -location {15566.660 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id3_0/u_ram_w16_l512_id3_0_mem} -location {16383.060 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id3_1/u_ram_w16_l512_id3_1_mem} -location {17199.460 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id4_0/u_ram_w16_l512_id4_0_mem} -location {18015.860 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id4_1/u_ram_w16_l512_id4_1_mem} -location {18832.260 14035.520} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id5_0/u_ram_w16_l512_id5_0_mem} -location {55.060 14888.720} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id5_1/u_ram_w16_l512_id5_1_mem} -location {871.460 14888.720} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id6_0/u_ram_w16_l512_id6_0_mem} -location {1687.860 14888.720} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id6_1/u_ram_w16_l512_id6_1_mem} -location {2504.260 14888.720} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id7_0/u_ram_w16_l512_id7_0_mem} -location {3320.660 14888.720} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id7_1/u_ram_w16_l512_id7_1_mem} -location {4137.060 14888.720} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id8_0/u_ram_w16_l512_id8_0_mem} -location {4953.460 14888.720} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id8_1/u_ram_w16_l512_id8_1_mem} -location {5769.860 14888.720} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id9_0/u_ram_w16_l512_id9_0_mem} -location {6586.260 14888.720} -orientation R0
place_macro -macro_name {inst_ram_w16_l512_id9_1/u_ram_w16_l512_id9_1_mem} -location {7402.660 14888.720} -orientation R0

set _blk [ord::get_db_block]
foreach _m {
  {inst_ram_w16_l32768_id0_0/u_ram_w16_l32768_id0_0_mem}
  {inst_ram_w16_l32768_id0_1/u_ram_w16_l32768_id0_1_mem}
  {inst_ram_w16_l32768_id1_0/u_ram_w16_l32768_id1_0_mem}
  {inst_ram_w16_l32768_id1_1/u_ram_w16_l32768_id1_1_mem}
  {inst_ram_w16_l512_id0_0/u_ram_w16_l512_id0_0_mem}
  {inst_ram_w16_l512_id0_1/u_ram_w16_l512_id0_1_mem}
  {inst_ram_w16_l512_id10_0/u_ram_w16_l512_id10_0_mem}
  {inst_ram_w16_l512_id10_1/u_ram_w16_l512_id10_1_mem}
  {inst_ram_w16_l512_id11_0/u_ram_w16_l512_id11_0_mem}
  {inst_ram_w16_l512_id11_1/u_ram_w16_l512_id11_1_mem}
  {inst_ram_w16_l512_id12_0/u_ram_w16_l512_id12_0_mem}
  {inst_ram_w16_l512_id12_1/u_ram_w16_l512_id12_1_mem}
  {inst_ram_w16_l512_id13_0/u_ram_w16_l512_id13_0_mem}
  {inst_ram_w16_l512_id13_1/u_ram_w16_l512_id13_1_mem}
  {inst_ram_w16_l512_id14_0/u_ram_w16_l512_id14_0_mem}
  {inst_ram_w16_l512_id14_1/u_ram_w16_l512_id14_1_mem}
  {inst_ram_w16_l512_id15_0/u_ram_w16_l512_id15_0_mem}
  {inst_ram_w16_l512_id15_1/u_ram_w16_l512_id15_1_mem}
  {inst_ram_w16_l512_id16_0/u_ram_w16_l512_id16_0_mem}
  {inst_ram_w16_l512_id16_1/u_ram_w16_l512_id16_1_mem}
  {inst_ram_w16_l512_id17_0/u_ram_w16_l512_id17_0_mem}
  {inst_ram_w16_l512_id17_1/u_ram_w16_l512_id17_1_mem}
  {inst_ram_w16_l512_id18_0/u_ram_w16_l512_id18_0_mem}
  {inst_ram_w16_l512_id18_1/u_ram_w16_l512_id18_1_mem}
  {inst_ram_w16_l512_id19_0/u_ram_w16_l512_id19_0_mem}
  {inst_ram_w16_l512_id19_1/u_ram_w16_l512_id19_1_mem}
  {inst_ram_w16_l512_id1_0/u_ram_w16_l512_id1_0_mem}
  {inst_ram_w16_l512_id1_1/u_ram_w16_l512_id1_1_mem}
  {inst_ram_w16_l512_id20_0/u_ram_w16_l512_id20_0_mem}
  {inst_ram_w16_l512_id20_1/u_ram_w16_l512_id20_1_mem}
  {inst_ram_w16_l512_id21_0/u_ram_w16_l512_id21_0_mem}
  {inst_ram_w16_l512_id21_1/u_ram_w16_l512_id21_1_mem}
  {inst_ram_w16_l512_id22_0/u_ram_w16_l512_id22_0_mem}
  {inst_ram_w16_l512_id22_1/u_ram_w16_l512_id22_1_mem}
  {inst_ram_w16_l512_id23_0/u_ram_w16_l512_id23_0_mem}
  {inst_ram_w16_l512_id23_1/u_ram_w16_l512_id23_1_mem}
  {inst_ram_w16_l512_id24_0/u_ram_w16_l512_id24_0_mem}
  {inst_ram_w16_l512_id24_1/u_ram_w16_l512_id24_1_mem}
  {inst_ram_w16_l512_id25_0/u_ram_w16_l512_id25_0_mem}
  {inst_ram_w16_l512_id25_1/u_ram_w16_l512_id25_1_mem}
  {inst_ram_w16_l512_id26_0/u_ram_w16_l512_id26_0_mem}
  {inst_ram_w16_l512_id26_1/u_ram_w16_l512_id26_1_mem}
  {inst_ram_w16_l512_id27_0/u_ram_w16_l512_id27_0_mem}
  {inst_ram_w16_l512_id27_1/u_ram_w16_l512_id27_1_mem}
  {inst_ram_w16_l512_id28_0/u_ram_w16_l512_id28_0_mem}
  {inst_ram_w16_l512_id28_1/u_ram_w16_l512_id28_1_mem}
  {inst_ram_w16_l512_id2_0/u_ram_w16_l512_id2_0_mem}
  {inst_ram_w16_l512_id2_1/u_ram_w16_l512_id2_1_mem}
  {inst_ram_w16_l512_id3_0/u_ram_w16_l512_id3_0_mem}
  {inst_ram_w16_l512_id3_1/u_ram_w16_l512_id3_1_mem}
  {inst_ram_w16_l512_id4_0/u_ram_w16_l512_id4_0_mem}
  {inst_ram_w16_l512_id4_1/u_ram_w16_l512_id4_1_mem}
  {inst_ram_w16_l512_id5_0/u_ram_w16_l512_id5_0_mem}
  {inst_ram_w16_l512_id5_1/u_ram_w16_l512_id5_1_mem}
  {inst_ram_w16_l512_id6_0/u_ram_w16_l512_id6_0_mem}
  {inst_ram_w16_l512_id6_1/u_ram_w16_l512_id6_1_mem}
  {inst_ram_w16_l512_id7_0/u_ram_w16_l512_id7_0_mem}
  {inst_ram_w16_l512_id7_1/u_ram_w16_l512_id7_1_mem}
  {inst_ram_w16_l512_id8_0/u_ram_w16_l512_id8_0_mem}
  {inst_ram_w16_l512_id8_1/u_ram_w16_l512_id8_1_mem}
  {inst_ram_w16_l512_id9_0/u_ram_w16_l512_id9_0_mem}
  {inst_ram_w16_l512_id9_1/u_ram_w16_l512_id9_1_mem}
  {inst_ram_w16_l8192_id0_0/u_ram_w16_l8192_id0_0_mem}
  {inst_ram_w16_l8192_id0_1/u_ram_w16_l8192_id0_1_mem}
  {inst_ram_w64_l256_id0/u_ram_w64_l256_id0_mem}
} {
  set _i [$_blk findInst $_m]
  if {$_i ne "NULL" && $_i ne ""} { $_i setPlacementStatus FIRM }
}

