#!/usr/bin/env bash
#
# Extract an ORFS-compatible config.mk for a HighTide design from the
# bazel-orfs flow's generated artifacts.
#
# The bazel-orfs rule writes one `<stage>.short.mk` per flow stage,
# each containing `export VAR?=VALUE` lines for every resolved ORFS
# env var the stage consumes. Different stages contribute different
# vars (synth → VERILOG_FILES / SDC_FILE; floorplan → CORE_UTILIZATION;
# final → GDS_ALLOW_EMPTY; etc.) — so this script forces a build of
# every stage, unions the export lines across all shortmks, drops the
# Bazel-internal ones, and emits a config.mk you can feed to upstream
# OpenROAD-flow-scripts (`make DESIGN_CONFIG=<this-file> ...`).
#
# Usage:
#   tools/bazel_to_config_mk.sh <design-dir-or-label> [output-file]
#
# Examples:
#   tools/bazel_to_config_mk.sh designs/asap7/lfsr
#   tools/bazel_to_config_mk.sh //designs/asap7/lfsr:lfsr   ./lfsr.config.mk
#   tools/bazel_to_config_mk.sh designs/asap7/liteeth/liteeth_mac_axi_mii
#
# Caveats:
# - VERILOG_FILES / SDC_FILE paths are workspace-relative. Run upstream
#   ORFS Make from the HighTide repo root (or symlink the paths in).
# - For designs that synthesize from dev-generated RTL (genrules), the
#   resolved paths point into bazel-out/. Use --define update_rtl=true
#   before extraction if you want fresh generated sources, or rely on
#   the committed release RTL by extracting without that flag (default).
# - PLATFORM_DIR is intentionally stripped — let ORFS Make derive it
#   from $(FLOW_HOME)/platforms/$(PLATFORM).

set -euo pipefail

usage() {
    sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//' >&2
    exit 1
}

[ $# -ge 1 ] && [ $# -le 2 ] || usage

input=$1
output=${2:-}

# --- Normalize the input to package + target name -------------------
case "$input" in
    //*:*)        # //designs/asap7/lfsr:lfsr
        label=${input#//}
        pkg=${label%:*}
        name=${label##*:}
        ;;
    //*)          # //designs/asap7/lfsr  (no :target → derive from BUILD.bazel)
        pkg=${input#//}
        name=""
        ;;
    *)            # designs/asap7/lfsr  (or with trailing /)
        pkg=${input%/}
        name=""
        ;;
esac

build_file="${pkg}/BUILD.bazel"
[ -f "$build_file" ] || {
    echo "ERROR: no $build_file" >&2
    exit 1
}

# If no target was supplied, read the name from the hightide_design()
# (or orfs_flow()) call in BUILD.bazel — first quoted value after `name =`.
if [ -z "$name" ]; then
    name=$(awk -F'"' '
        /hightide_design\(|orfs_flow\(/   { in_call = 1 }
        in_call && /name[[:space:]]*=/    { print $2; exit }
    ' "$build_file")
    [ -n "$name" ] || {
        echo "ERROR: could not find name = \"...\" in $build_file" >&2
        exit 1
    }
fi

# --- Build every stage so all shortmks exist on disk ----------------
stages=(synth floorplan place cts grt route final)
targets=()
for s in "${stages[@]}"; do targets+=("//${pkg}:${name}_${s}"); done

echo "Building all stages of //${pkg}:${name} ..." >&2
bazel build "${targets[@]}" >&2

# --- Locate the result dir + collect every short.mk -----------------
results_root="bazel-bin/${pkg}/results"
[ -d "$results_root" ] || {
    echo "ERROR: $results_root missing after build" >&2
    exit 1
}

mapfile -t shortmks < <(find "$results_root" -name '*.short.mk' -type f 2>/dev/null | sort)
[ "${#shortmks[@]}" -gt 0 ] || {
    echo "ERROR: no *.short.mk under $results_root" >&2
    exit 1
}

# --- Filter + union -------------------------------------------------
# Drop Bazel-internal vars that ORFS Make computes itself or doesn't want.
SKIP_VARS='^(WORK_HOME|FLOW_VARIANT|LEC_CHECK|GENERATE_ARTIFACTS_ON_FAILURE|PLATFORM_DIR)$'

# Vars whose values are file/directory paths and must be absolute so the
# config.mk works no matter where `make` is run from. Multi-value vars
# (VERILOG_FILES, ADDITIONAL_LEFS/LIBS) are split on whitespace and each
# token is absolutized independently.
PATH_VARS='^(SDC_FILE|FOOTPRINT_TCL|IO_CONSTRAINTS|PDN_TCL|MACROS_VERILOG|MACROS_LIB|VERILOG_FILES|ADDITIONAL_LEFS|ADDITIONAL_LIBS|ADDITIONAL_GDS|ADDITIONAL_LIB_DIRS|PRE_CTS_TCL|PRE_GRT_TCL|PRE_REPAIR_TIMING_TCL|FASTROUTE_TCL)$'

repo_root=$(pwd -P)

emit() {
    cat <<EOF
# Generated by tools/bazel_to_config_mk.sh from BUILD.bazel.
# Source : //${pkg}:${name}
# Reproduce:
#   bazel build //${pkg}:${name}_final
#   tools/bazel_to_config_mk.sh ${pkg}
#
# Paths are absolute (anchored at ${repo_root}) so this config.mk works
# from any directory:
#   make -C OpenROAD-flow-scripts/flow DESIGN_CONFIG=<this-file>

EOF

    # `export VAR?=VALUE` → keep the first occurrence of each VAR.
    # For path-valued vars, prepend repo_root to every relative token.
    grep -h '^export ' "${shortmks[@]}" \
        | awk -v skip="$SKIP_VARS" -v pvars="$PATH_VARS" -v root="$repo_root" '
            function absify(v,    parts, n, i, out) {
                n = split(v, parts, " ")
                out = ""
                for (i = 1; i <= n; i++) {
                    if (parts[i] == "") continue
                    if (parts[i] ~ /^\//) {           # already absolute
                        out = out (out=="" ? "" : " ") parts[i]
                    } else {
                        out = out (out=="" ? "" : " ") root "/" parts[i]
                    }
                }
                return out
            }
            {
                p = index($0, "?=")
                if (p == 0) next
                key = substr($0, 1, p - 1)
                val = substr($0, p + 2)
                sub(/^export /, "", key)
                sub(/[[:space:]]+$/, "", key)
                if (key ~ skip)  next
                if (seen[key]++) next
                if (key ~ pvars) val = absify(val)
                printf "export %s?=%s\n", key, val
            }' \
        | sort
}

if [ -z "$output" ]; then
    emit
else
    emit > "$output"
    echo "Wrote $output" >&2
fi
