#!/usr/bin/env python3
"""Generate a fixed-grid MACRO_PLACEMENT_TCL from an ODB macro dump.

Design-agnostic version of the cnn-sky130hd grid fix. sky130hd's coarse
routing pitch + fakeram macros that put all signal pins on their bottom
(met2) edge means RTLMP's pin-edge-blind, mixed-orientation clustering
collides adjacent macros' met2 escape lanes -> localized capacity:0
overflow that no knob tuning clears. The fix: force every macro to R0
(pins uniformly south) on a regular grid with a routing channel below
every row, so each macro's pin edge always faces clear routing space.
Macros are set FIRM so the rtl_macro_placer ORFS runs *after* sourcing
MACRO_PLACEMENT_TCL leaves them alone.

Input: a dump produced by tools/dump_macros.tcl, lines of the form
  MACRO <inst> | <master> | <orient> | x y | WxH | status
plus one  CORE_UM x0 y0 x1 y1  line.  W/H come straight from the dump so
no LEF parsing or per-design size table is needed.

Usage:
  gen_macro_grid.py <dump.txt> <out.tcl> [--margin M] [--gap-x GX]
                     [--chan CH] [--chan-small CHS]
"""
import argparse
import sys


def load(path):
    core = None
    macros = []  # (inst, master, w, h)
    for line in open(path):
        if line.startswith("CORE_UM"):
            _, x0, y0, x1, y1 = line.split()
            core = (float(x0), float(y0), float(x1), float(y1))
        elif line.startswith("MACRO"):
            parts = [p.strip() for p in line[5:].split("|")]
            inst, master = parts[0], parts[1]
            w, h = (float(v) for v in parts[4].split("x"))
            macros.append((inst, master, w, h))
    if core is None:
        sys.exit("dump has no CORE_UM line")
    return core, macros


def pack_rows(macros, x0, x_limit, gap_x):
    """Group like-sized macros into left-aligned rows, largest area first."""
    by_master = {}
    for m in macros:
        by_master.setdefault(m[1], []).append(m)
    order = sorted(by_master, key=lambda k: by_master[k][0][2] * by_master[k][0][3],
                   reverse=True)
    rows = []
    for master in order:
        group = by_master[master]
        w = group[0][2]
        per_row = max(1, int((x_limit - x0 + gap_x) // (w + gap_x)))
        for i in range(0, len(group), per_row):
            rows.append(group[i:i + per_row])
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("dump")
    ap.add_argument("out")
    ap.add_argument("--margin", type=float, default=50.0)
    ap.add_argument("--gap-x", type=float, default=300.0)
    ap.add_argument("--chan", type=float, default=500.0,
                    help="routing channel below each row (um)")
    args = ap.parse_args()

    (cx0, cy0, cx1, cy1), macros = load(args.dump)
    x0 = cx0 + args.margin
    x_limit = cx1 - args.margin
    rows = pack_rows(macros, x0, x_limit, args.gap_x)

    out = [
        "# AUTO-GENERATED by tools/gen_macro_grid.py",
        "# Fixed grid: every macro R0 (pins uniformly south), a routing",
        "# channel below every row so each macro's met2 pin edge faces",
        "# clear space. Macros FIRM so the post-source rtl_macro_placer",
        "# leaves them alone. See the script header for the rationale.",
        "",
    ]
    # Start one channel up so row 1's pin edge also faces a channel.
    y = cy0 + args.chan
    for row in rows:
        rh = max(m[3] for m in row)
        x = x0
        for inst, master, w, h in row:
            out.append(
                f"place_macro -macro_name {{{inst}}} "
                f"-location {{{x:.3f} {y:.3f}}} -orientation R0")
            x += w + args.gap_x
        y += rh + args.chan

    top = y
    if top >= cy1 - args.margin:
        sys.exit(f"grid overflows core: top={top:.1f} >= {cy1 - args.margin:.1f}"
                 f" (loosen --gap-x / --chan or widen the die)")

    out += ["", "set _blk [ord::get_db_block]", "foreach _m {"]
    out += [f"  {{{m[0]}}}" for m in macros]
    out += ["} {", "  set _i [$_blk findInst $_m]",
            "  if {$_i ne \"NULL\" && $_i ne \"\"} { $_i setPlacementStatus FIRM }",
            "}", ""]

    with open(args.out, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {args.out}: {len(macros)} macros, {len(rows)} rows, "
          f"grid_top={top:.1f}um, core_y1={cy1:.1f}um")


if __name__ == "__main__":
    main()
